on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create binaries and push to latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache layer for xwin
        uses: actions/cache@v4.0.2
        with:
          path: /xwin
          key: ${{ runner.os }}-xwin-extracted-sdk-crt
          save-always: true

      - name: Generate Windows build env
        uses: ./.github/create-windows-build-env

      - name: Generate the artifacts
        uses: skx/github-action-build@master
        
      - name: Upload the Linux artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '/github/workspace/target/release/automation-test'
      - name: Upload the Windows artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '/github/workspace/target/release/automation-test.exe'
