on:
  release:
    types: [created]
name: Handle Release
runs-on: self-hosted
jobs:
  generate:
    name: Create binaries and push to latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Cache layer for xwin
        uses: actions/cache@v4.0.2
        with:
          path: /xwin
          key: ${{ runner.os }}-xwin-extracted-sdk-crt
          save-always: true
        
      - name: Build and upload binaries
        uses: ./.github/build-and-upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
